# Generated by Django 3.2.8 on 2024-03-03 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taddress',
            fields=[
                ('code_address', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('gate', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('door', models.CharField(blank=True, max_length=10)),
                ('local', models.CharField(blank=True, max_length=10)),
                ('cpostal', models.CharField(blank=True, max_length=10)),
                ('wo_lift', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Taddress',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tconnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('token_ph', models.CharField(max_length=200)),
                ('connect', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=999999)),
            ],
            options={
                'db_table': 'Tconnect',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('token_access', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Tsessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Twolifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('lift', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Twolifts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tsenders',
            fields=[
                ('code_sender', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=555555555)),
                ('token_ph', models.CharField(blank=True, max_length=200)),
                ('qualification', models.IntegerField(default=0)),
                ('code_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PIP01app.taddress')),
            ],
            options={
                'db_table': 'Tsenders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Triders',
            fields=[
                ('code_rider', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surnames', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=555555555)),
                ('token_ph', models.CharField(blank=True, max_length=200)),
                ('connect', models.BooleanField(default=False)),
                ('code_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PIP01app.taddress')),
            ],
            options={
                'db_table': 'Triders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Torders',
            fields=[
                ('code_order', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pay', models.FloatField(default=3.8)),
                ('application', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='PIP01app.taddress')),
                ('code_rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PIP01app.triders')),
                ('code_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PIP01app.tsenders')),
            ],
            options={
                'db_table': 'Torders',
                'managed': True,
            },
        ),
    ]
